version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  somleng:
    image: public.ecr.aws/somleng/somleng
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DASHBOARD_URL_HOST: "http://dashboard.lvh.me:3000"
      AHN_HOST: "http://somleng-switch:8080"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - somleng-switch
    networks:
      default:
        aliases:
          - api.somleng.dev
    healthcheck:
      test: ["CMD-SHELL", "wget --server-response --spider --quiet http://localhost:3000/health_checks 2>&1 | grep '200 OK' > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10

  somleng-switch:
    image: public.ecr.aws/somleng/somleng-switch
    environment:
      AHN_CORE_HOST: freeswitch
      AHN_CORE_HTTP_PORT: 8080
      CALL_PLATFORM_HOST: "http://api.somleng.dev:3000"
    depends_on:
      - freeswitch
    healthcheck:
      test: ["CMD-SHELL", "wget --server-response --spider --quiet http://localhost:8080/health_checks 2>&1 | grep '200 OK' > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10

  freeswitch:
    image: public.ecr.aws/somleng/somleng-switch-freeswitch
    environment:
      - FS_DATABASE_HOST=db
      - FS_MOD_JSON_CDR_URL=http://api.somleng.dev:3000/services/call_data_records
      - FS_EXTERNAL_SIP_IP
      - FS_EXTERNAL_RTP_IP
    ports:
      - "5060:5060/udp"
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "nc -z -w 5 localhost 5222"]
      interval: 10s
      timeout: 5s
      retries: 10
