version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  twilreapi:
    image: public.ecr.aws/somleng/twilreapi
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      APP_URL_HOST: "http://twilreapi:3000"
      AHN_HOST: "http://adhearsion:8080"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - adhearsion

  adhearsion:
    image: public.ecr.aws/somleng/somleng-switch
    environment:
      AHN_CORE_HOST: freeswitch
      CALL_PLATFORM_HOST: "http://twilreapi:3000"
    depends_on:
      - freeswitch

  freeswitch:
    image: public.ecr.aws/somleng/somleng-switch-freeswitch
    environment:
      - FS_DATABASE_HOST=db
      - FS_MOD_JSON_CDR_URL=http://twilreapi:3000/services/call_data_records
      - FS_EXTERNAL_SIP_IP
      - FS_EXTERNAL_RTP_IP
    ports:
      - "5060:5060/udp"
    depends_on:
      - db
