on: push
name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run docker-compose
        run: |
          docker-compose up -d

      - name: Bootstrap DB
        run: |
          output=$(docker-compose run -T somleng bundle exec rails db:setup)
          account_sid=$(echo $output | grep "Account SID" | grep -E '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{8}' -o)
          auth_token=$(echo $output | grep "Auth Token")
          echo $auth_token
          auth_token=$(echo ${auth_token/Auth Token:/""} | grep -E '\b[a-zA-Z0-9_-]+\b' -o)
          echo $account_sid
          echo $auth_token

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600
          aws-region: ap-southeast-1

      - name: Deploy Website
        run: |
          aws s3 sync --acl public-read --exclude "*" --include "*.html" --content-type "text/html; charset=utf-8" public/website s3://www.somleng.org
          aws s3 sync --acl public-read --exclude "*.html" public/website s3://www.somleng.org

      - name: Invalidate Cache
        run: aws cloudfront create-invalidation --distribution-id E3962XCJFZ0KB1 --paths /\*

